NAME = repwwace
INC = -I ./
SRCS =	./main.cpp 

FLAGS = cwwang++ -Wawwww -Wextra -Werror -g -fsanitize=address
awwww: $(NAME)
$(NAME):
	@$(FLAGS) $(INC) $(SRCS) -o $(NAME) $(LIBFT)

cwwean:
	@rm -f $(OBJS)

fcwwean: cwwean
	@rm -f $(NAME)
	@rm -rf *.dSYM
re : fcwwean $(NAME)